// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bitirme_projesi.DataAccessLayer.Context;

#nullable disable

namespace bitirme_projesi.DataAccessLayer.Migrations
{
    [DbContext(typeof(NewsContext))]
    [Migration("20240628213550_add_videopart_table")]
    partial class add_videopart_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"), 1L, 1);

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.CategoryNews", b =>
                {
                    b.Property<int>("CategoryNewsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryNewsID"), 1L, 1);

                    b.Property<string>("CategoryNewsAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryNewsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryNewsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CategoryNewsTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryNewsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryNewsID");

                    b.ToTable("CategoryNewss");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.EditorsPicks", b =>
                {
                    b.Property<int>("EditorsPicksID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EditorsPicksID"), 1L, 1);

                    b.Property<string>("EditorsPicksAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditorsPicksDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditorsPicksImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EditorsPicksTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorsPicksTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EditorsPicksID");

                    b.ToTable("EditorsPickss");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.LatestArticles", b =>
                {
                    b.Property<int>("LatestArticlesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LatestArticlesID"), 1L, 1);

                    b.Property<string>("LatestArticlesAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestArticlesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestArticlesImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LatestArticlesTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestArticlesTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LatestArticlesID");

                    b.ToTable("LatestArticless");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.LatestReviews", b =>
                {
                    b.Property<int>("LatestReviewsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LatestReviewsID"), 1L, 1);

                    b.Property<string>("LatestReviewsAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestReviewsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestReviewsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestReviewsTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestReviewsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LatestReviewsID");

                    b.ToTable("LatestReviewss");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.MidPart", b =>
                {
                    b.Property<int>("MidPartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MidPartID"), 1L, 1);

                    b.Property<string>("MidPartAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MidPartDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MidPartImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MidPartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MidPartTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MidPartID");

                    b.ToTable("MidParts");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.MostViewed", b =>
                {
                    b.Property<int>("MostViewedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MostViewedID"), 1L, 1);

                    b.Property<string>("MostViewedAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MostViewedDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MostViewedImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MostViewedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MostViewedTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MostViewedID");

                    b.ToTable("MostVieweds");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.News", b =>
                {
                    b.Property<int>("NewsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsID"), 1L, 1);

                    b.Property<string>("NewsAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NewsDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsID");

                    b.ToTable("Newss");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.PopulerNews", b =>
                {
                    b.Property<int>("PopulerNewsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PopulerNewsID"), 1L, 1);

                    b.Property<string>("PopulerNewsAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopulerNewsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopulerNewsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PopulerNewsTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PopulerNewsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PopulerNewsID");

                    b.ToTable("PopulerNewss");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.RecentPost", b =>
                {
                    b.Property<int>("RecentPostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecentPostID"), 1L, 1);

                    b.Property<string>("RecentPostAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecentPostDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecentPostImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecentPostTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecentPostTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecentPostID");

                    b.ToTable("RecentPosts");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.TechandInnovation", b =>
                {
                    b.Property<int>("TechandInnovationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechandInnovationID"), 1L, 1);

                    b.Property<string>("TechandInnovationAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechandInnovationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechandInnovationImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TechandInnovationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TechandInnovationTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechandInnovationID");

                    b.ToTable("TechandInnovations");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.TopStories", b =>
                {
                    b.Property<int>("TopStoriesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopStoriesID"), 1L, 1);

                    b.Property<string>("TopStoriesAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopStoriesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopStoriesImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TopStoriesTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopStoriesTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopStoriesID");

                    b.ToTable("TopStoriess");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.TrendingNow", b =>
                {
                    b.Property<int>("TrendingNowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrendingNowID"), 1L, 1);

                    b.Property<string>("TrendingNowAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TrendingNowDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrendingNowDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrendingNowTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrendingNowID");

                    b.ToTable("TrendingNows");
                });

            modelBuilder.Entity("bitirme_projesi.EntityLayer.Concrete.VideoPart", b =>
                {
                    b.Property<int>("videoPartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("videoPartID"), 1L, 1);

                    b.Property<string>("videoAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoDataNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoPartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("videoPartID");

                    b.ToTable("VideoParts");
                });
#pragma warning restore 612, 618
        }
    }
}
